version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /deploy/github/log/leaf_validator
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /deploy/github/log/sequence_and_integrate
  schedule:
    interval: daily

